# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-12 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_myuser_blood_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='myuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='height',
            field=models.IntegerField(default=160),
        ),
        migrations.AddField(
            model_name='myuser',
            name='illness',
            field=models.IntegerField(choices=[(1, 'Bəli'), (2, 'Xeyr')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='illness1',
            field=models.IntegerField(choices=[(1, 'Bəli'), (2, 'Xeyr')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='illness2',
            field=models.IntegerField(choices=[(1, 'Bəli'), (2, 'Xeyr')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='last_blood_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='weight',
            field=models.IntegerField(default=50),
        ),
    ]
