# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-13 12:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20180612_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='blood_group',
            field=models.IntegerField(choices=[(1, 'I +'), (2, 'II +'), (3, 'III +'), (4, 'IV + '), (5, 'I -'), (6, 'II -'), (7, 'III -'), (8, 'IV -')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(code='invalid username', message='lalala', regex='^[a-zA-Z0-9@.+-]*$')], verbose_name='İstifadəçi adı'),
        ),
    ]
